#!/bin/sh /etc/rc.common
USE_PROCD=1

START=97
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/optimization-daemon.sh
    procd_set_param respawn 30 5 100
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/wifi-ac-optimizationd.pid
    procd_close_instance
}
